# Generated by Django 4.0.4 on 2022-06-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_device_room_number_alter_device_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobil', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
