# Generated by Django 4.0.4 on 2022-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('Address', models.CharField(max_length=60)),
                ('SSN', models.DecimalField(decimal_places=14, max_digits=14)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('Age', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Mobil', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
