# Generated by Django 4.0.4 on 2022-05-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Age',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='SSN',
            field=models.PositiveIntegerField(max_length=14),
        ),
    ]
