# Generated by Django 4.0.4 on 2022-05-31 21:15

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_age_alter_doctor_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=re.RegexFlag['MULTILINE'], max_length=1),
        ),
    ]
