# Generated by Django 4.0.4 on 2022-05-31 22:06

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('Mobil', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('Address', models.CharField(max_length=60)),
                ('SSN', models.PositiveIntegerField(max_length=14)),
                ('Age', models.PositiveIntegerField(max_length=2)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=re.RegexFlag['MULTILINE'], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('Mobil', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('Address', models.CharField(max_length=60)),
                ('SSN', models.PositiveIntegerField(max_length=14)),
                ('Age', models.PositiveIntegerField(max_length=2)),
                ('Examinations', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('Medical_status', models.TextField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=re.RegexFlag['MULTILINE'], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Mobil',
            field=models.CharField(max_length=30),
        ),
    ]
