# Generated by Django 4.0.4 on 2022-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_nurse_patient_alter_doctor_mobil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Medical_status',
            new_name='Symptoms',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='SSN',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='SSN',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='SSN',
            field=models.PositiveIntegerField(),
        ),
    ]
