# Generated by Django 4.0.4 on 2022-06-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_medical_status_patient_symptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Examinations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Mobil',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='SSN',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Symptoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Confirm_Password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='Confirm_Password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Confirm_Password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
