# Generated by Django 4.0.4 on 2022-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_doctor_gender_remove_doctor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
