# Generated by Django 4.0.4 on 2022-06-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
