# Generated by Django 4.0.4 on 2022-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='upload',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
